In [1]:
import numpy as np

In [2]:
a = np.arange(1, 10).reshape((3, 3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.sum(a, axis=0)

array([12, 15, 18])

In [5]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [6]:
np.flip(a, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])